/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  connection_id: string;
  estimated_block_interval_seconds: number;
  fee_bps_block_increment: number;
  fee_payment_cooldown_blocks: number;
  icq_update_interval: number;
  initial_validator_set: string[];
  initial_validator_weights: number[];
  interchain_tx_timeout_seconds: number;
  max_fee_bps: number;
  max_unbonding_entries: number;
  remote_denom: string;
  remote_denom_decimals: number;
  transfer_in_channel: string;
  transfer_in_timeout_seconds: number;
  transfer_out_channel: string;
  transfer_out_timeout_seconds: number;
  unbonding_period: number;
}
export type ExecuteMsg = ExecuteMsg1 | ExecuteMsg2 | StrategyExecuteMsg;
export type ExecuteMsg1 = {
  transfer_admin_role: {
    next_admin: string;
  };
} | {
  claim_admin_role: {};
} | {
  cancel_role_transfer: {};
};
export type ExecuteMsg2 = {
  deposit: {};
} | {
  donate: {};
} | {
  redeem: {
    recipient: string;
  };
} | {
  start_unbond: {};
} | {
  claim: {};
};
export type StrategyExecuteMsg = {
  reconcile: {
    fee_recipient?: string | null;
  };
} | {
  receive_undelegated: {};
} | {
  restore_ica: {
    id: string;
  };
} | {
  restore_icq: {
    id: string;
  };
} | {
  reset_max_msg_count: {};
} | {
  update_config: {
    estimated_block_interval_seconds?: number | null;
    fee_bps_block_increment?: number | null;
    fee_payment_cooldown_blocks?: number | null;
    icq_update_interval?: number | null;
    interchain_tx_timeout_seconds?: number | null;
    max_fee_bps?: number | null;
    transfer_in_timeout_seconds?: number | null;
    transfer_out_timeout_seconds?: number | null;
  };
};
export type QueryMsg = QueryMsg1 | QueryMsg2 | StrategyQueryMsg;
export type QueryMsg1 = {
  current_admin: {};
} | {
  pending_admin: {};
};
export type QueryMsg2 = {
  state: {};
} | {
  pending_unbonding: {
    address?: string | null;
  };
} | {
  active_unbondings: {
    address?: string | null;
  };
} | {
  claimable: {
    address: string;
  };
} | {
  underlying_asset_decimals: {};
} | {
  deposit_asset: {};
} | {
  shares_asset: {};
};
export type StrategyQueryMsg = {
  config: {};
} | {
  metadata: {};
} | {
  reconcile_state: {};
} | {
  validator_set: {};
};
export type Uint128 = string;
export interface ActiveUnbondingsResponse {
  unbondings: UnbondingStatus[];
}
export interface UnbondingStatus {
  amount: Uint128;
  end: number;
  start: number;
}
export interface ClaimableResponse {
  amount: Uint128;
}
export interface Config {
  connection_id: string;
  estimated_block_interval_seconds: number;
  fee_bps_block_increment: number;
  fee_payment_cooldown_blocks: number;
  icq_update_interval: number;
  interchain_tx_timeout_seconds: number;
  max_fee_bps: number;
  max_unbonding_entries: number;
  remote_denom: string;
  remote_denom_decimals: number;
  transfer_in_channel: string;
  transfer_in_timeout_seconds: number;
  transfer_out_channel: string;
  transfer_out_timeout_seconds: number;
  unbonding_period: number;
}
export interface CurrentAdminResponse {
  current_admin?: string | null;
}
export interface DepositAssetResponse {
  denom: string;
}
export interface Metadata {
  available_to_claim: Uint128;
  delegated: Uint128;
  delegations_icq?: number | null;
  ibc_deposit_asset: string;
  inflight_delegation: Uint128;
  inflight_deposit: Uint128;
  inflight_fee_payable: Uint128;
  inflight_rewards_receivable: Uint128;
  inflight_unbond: Uint128;
  last_main_ica_balance_icq_update?: number | null;
  last_reconcile_height?: number | null;
  last_unbond_timestamp?: number | null;
  last_used_main_ica_balance_icq_update?: number | null;
  main_ica_address?: string | null;
  main_ica_balance_icq?: number | null;
  max_ibc_msg_count: number;
  minimum_unbond_interval: number;
  msg_issued_count: number;
  msg_success_count: number;
  pending_deposit: Uint128;
  pending_unbond: Uint128;
  rewards_ica_address?: string | null;
  rewards_ica_balance_icq?: number | null;
  total_actual_unbonded: Uint128;
  total_expected_unbonded: Uint128;
  unbonding_ack_count?: number | null;
  unbonding_issued_count?: number | null;
}
export interface PendingAdminResponse {
  pending_admin?: string | null;
}
export interface PendingUnbondingResponse {
  amount: Uint128;
  start_hint?: number | null;
}
export interface ReconcileState {
  cost: Uint128;
  fee_recipient?: string | null;
  phase: string;
  state: string;
  trigger_address?: string | null;
}
export interface SharesAssetResponse {
  denom: string;
}
export interface StateResponse {
  total_deposits: Uint128;
  total_issued_shares: Uint128;
}
export interface UnderlyingAssetDecimalsResponse {
  decimals: number;
}
export interface ValidatorSet {
  size: number;
  validators: string[];
  weights: string[];
}