/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  lst_decimals: number;
  lst_denom: string;
  lst_redemption_rate_oracle: string;
  underlying_decimals: number;
}
export type ExecuteMsg = ExecuteMsg1 | ExecuteMsg2 | StrategyExecuteMsg;
export type ExecuteMsg1 = {
  transfer_admin_role: {
    next_admin: string;
  };
} | {
  claim_admin_role: {};
} | {
  cancel_role_transfer: {};
};
export type ExecuteMsg2 = {
  deposit: {};
} | {
  donate: {};
} | {
  redeem: {
    recipient: string;
  };
} | {
  start_unbond: {};
} | {
  claim: {};
};
export type StrategyExecuteMsg = {
  set_redemption_rate_oracle: {
    oracle: string;
  };
};
export type QueryMsg = QueryMsg1 | QueryMsg2 | StrategyQueryMsg;
export type QueryMsg1 = {
  current_admin: {};
} | {
  pending_admin: {};
};
export type QueryMsg2 = {
  state: {};
} | {
  pending_unbonding: {
    address?: string | null;
  };
} | {
  active_unbondings: {
    address?: string | null;
  };
} | {
  unbonding_log_metadata: {
    address: string;
  };
} | {
  claimable: {
    address: string;
  };
} | {
  underlying_asset_decimals: {};
} | {
  deposit_asset: {};
} | {
  shares_asset: {};
};
export type StrategyQueryMsg = {
  metadata: {};
};
export type Uint128 = string;
export interface ActiveUnbondingsResponse {
  unbondings: UnbondingStatus[];
}
export interface UnbondingStatus {
  amount: Uint128;
  end: number;
  start: number;
}
export interface ClaimableResponse {
  amount: Uint128;
}
export interface CurrentAdminResponse {
  current_admin?: string | null;
}
export interface DepositAssetResponse {
  denom: string;
}
export interface MetadataResponse {
  active_lst_balance: Uint128;
  claimable_lst_balance: Uint128;
  lst_decimals: number;
  lst_denom: string;
  lst_redemption_rate_oracle: string;
  underlying_decimals: number;
}
export interface PendingAdminResponse {
  pending_admin?: string | null;
}
export interface PendingUnbondingResponse {
  amount: Uint128;
  start_hint?: number | null;
}
export interface SharesAssetResponse {
  denom: string;
}
export interface StateResponse {
  total_deposits: Uint128;
  total_issued_shares: Uint128;
}
export interface UnbondingLogMetadata {
  first_entered_batch?: number | null;
  last_claimed_batch?: number | null;
  last_committed_batch_id?: number | null;
  last_entered_batch?: number | null;
}
export interface UnderlyingAssetDecimalsResponse {
  decimals: number;
}