/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin?: string | null;
  hub_address: string;
}
export type ExecuteMsg = ExecuteMsg1 | ProxyMsg;
export type ExecuteMsg1 = {
  transfer_admin_role: {
    next_admin: string;
  };
} | {
  claim_admin_role: {};
} | {
  cancel_role_transfer: {};
};
export type ProxyMsg = {
  set_config: {
    individual_deposit_cap?: Uint128 | null;
    total_deposit_cap?: Uint128 | null;
    total_mint_cap?: Uint128 | null;
    vault: string;
  };
} | {
  deposit: {
    vault: string;
  };
} | {
  mint: {
    vault: string;
  };
};
export type Uint128 = string;
export type QueryMsg = QueryMsg1 | ProxyQueryMsg;
export type QueryMsg1 = {
  current_admin: {};
} | {
  pending_admin: {};
};
export type ProxyQueryMsg = {
  config: {
    vault: string;
  };
} | {
  vault_metadata: {
    vault: string;
  };
} | {
  deposit_amount: {
    account: string;
    vault: string;
  };
};
export interface ConfigResponse {
  hub_address: string;
  individual_deposit_cap: Uint128;
  total_deposit_cap: Uint128;
  total_mint_cap: Uint128;
}
export interface CurrentAdminResponse {
  current_admin?: string | null;
}
export interface DepositAmountResponse {
  amount: Uint128;
}
export interface PendingAdminResponse {
  pending_admin?: string | null;
}
export interface MetadataResponse {
  total_deposit: Uint128;
  total_mint: Uint128;
}