/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  admin?: string | null;
  hub_address: string;
  individual_deposit_cap: Uint128;
  total_deposit_cap: Uint128;
  total_mint_cap: Uint128;
}
export type ExecuteMsg = {
  set_admin: {
    address: string;
  };
} | {
  set_config: {
    individual_deposit_cap?: Uint128 | null;
    total_deposit_cap?: Uint128 | null;
    total_mint_cap?: Uint128 | null;
  };
} | {
  deposit: {
    vault: string;
  };
} | {
  mint: {
    vault: string;
  };
};
export type QueryMsg = {
  config: {};
} | {
  vault_metadata: {
    vault: string;
  };
} | {
  deposit_amount: {
    account: string;
    vault: string;
  };
};
export interface ConfigResponse {
  admin: string;
  hub_address: string;
  individual_deposit_cap: Uint128;
  total_deposit_cap: Uint128;
  total_mint_cap: Uint128;
}
export interface DepositAmountResponse {
  amount: Uint128;
}
export interface MetadataResponse {
  total_deposit: Uint128;
  total_mint: Uint128;
}