/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  set_whitelisted: {
    address: string;
    whitelisted: boolean;
  };
} | {
  set_redemption_rate: {
    rate: Decimal;
  };
};
export type Decimal = string;
export type QueryMsg = {
  redemption_rate: {};
};
export interface RedemptionRateResponse {
  rate: Decimal;
}