/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  hub_address: string;
}
export type ExecuteMsg = ExecuteMsg1 | ProxyUserMsg | ProxyAdminMsg;
export type ExecuteMsg1 = {
  transfer_admin_role: {
    next_admin: string;
  };
} | {
  claim_admin_role: {};
} | {
  cancel_role_transfer: {};
};
export type ProxyUserMsg = {
  process_head: {
    vault: string;
  };
} | {
  redeem: {
    vault: string;
  };
} | {
  cancel_entry: {
    index: number;
    vault: string;
  };
} | {
  cancel_all: {
    vault: string;
  };
};
export type ProxyAdminMsg = {
  force_cancel_entry: {
    index: number;
    vault: string;
  };
};
export type QueryMsg = QueryMsg1 | ProxyQueryMsg;
export type QueryMsg1 = {
  current_admin: {};
} | {
  pending_admin: {};
};
export type ProxyQueryMsg = {
  config: {};
} | {
  all_queue_entries: {
    limit?: number | null;
    start_index?: number | null;
    vault: string;
  };
} | {
  owner_queue_entries: {
    address: string;
    limit?: number | null;
    start?: number | null;
    vault: string;
  };
} | {
  queue_entry: {
    index: number;
    vault: string;
  };
};
export type Uint128 = string;
export interface QueueEntriesResponse {
  entries: QueueEntry[];
}
export interface QueueEntry {
  address: string;
  amount: Uint128;
  index: number;
}
export interface ConfigResponse {
  hub_address: string;
}
export interface CurrentAdminResponse {
  current_admin?: string | null;
}
export interface PendingAdminResponse {
  pending_admin?: string | null;
}
export interface QueueEntryResponse {
  amount_in_front: Uint128;
  entry: QueueEntry;
  position_in_queue: number;
}