[package]
name    = "num"
version = "0.0.0"
edition = "2021"

[lib]
path    = "lib.rs"
doctest = false

[dependencies]
serde       = { workspace = true, features = [ "derive" ] }
uint        = { workspace = true }
